/**
 * Regenerates `src/lib/emoji/full-data.ts` from unicode-emoji-json.
 *
 * The output is committed so the app has no runtime dependency and no network
 * fetch — a picker that can't open offline is useless in a PWA. Run with
 * `vp run emoji`.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const byEmoji = require("unicode-emoji-json/data-by-emoji.json") as Record<
  string,
  { name: string; slug: string; group: string; emoji_version: string }
>;
const ordered = require("unicode-emoji-json/data-ordered-emoji.json") as string[];

/**
 * Emoji newer than this render as tofu on devices that haven't shipped the
 * font update. A picker entry you can't see is worse than a missing one,
 * because you might still pick it and then never recognise the thing again.
 */
const MAX_EMOJI_VERSION = 15.0;

/** Skin-tone variants are excluded upstream; this drops the ones we can't show. */
const rows: [char: string, name: string, group: string][] = [];
const groups: string[] = [];
const groupIndex = new Map<string, number>();

let skipped = 0;
for (const char of ordered) {
  const entry = byEmoji[char];
  if (!entry) continue;
  if (Number.parseFloat(entry.emoji_version) > MAX_EMOJI_VERSION) {
    skipped += 1;
    continue;
  }
  if (!groupIndex.has(entry.group)) {
    groupIndex.set(entry.group, groups.length);
    groups.push(entry.group);
  }
  rows.push([char, entry.name, String(groupIndex.get(entry.group))]);
}

// Stored as tuples rather than objects: 1900 repetitions of `{"char":…,
// "name":…}` costs more than the data itself, and this file ships to every
// user. Group is an index into a small lookup for the same reason.
const body = rows
  .map(([char, name, group]) => `["${char}","${escape(name)}",${group}]`)
  .join(",\n  ");

const out = `// GENERATED by scripts/build-emoji.ts — do not edit.
// Source: unicode-emoji-json. Emoji up to version ${String(MAX_EMOJI_VERSION)}.

/** Unicode's own top-level groupings, used as the picker's category chips. */
export const FULL_GROUPS: string[] = ${JSON.stringify(groups, null, 0)};

/** [character, name, index into FULL_GROUPS] */
export type FullEmojiRow = [string, string, number];

export const FULL_EMOJI: FullEmojiRow[] = [
  ${body},
];
`;

const target = join(import.meta.dirname, "..", "src", "lib", "emoji", "full-data.ts");
await writeFile(target, out);
console.log(
  `Wrote ${String(rows.length)} emoji in ${String(groups.length)} groups ` +
    `(skipped ${String(skipped)} newer than Emoji ${String(MAX_EMOJI_VERSION)})`,
);

function escape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
