/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as TabsInsightsRouteImport } from './routes/_tabs.insights'
import { Route as TabsManageRouteImport } from './routes/_tabs.manage'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsInsightsRoute = TabsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TabsRoute,
} as any)
const TabsManageRoute = TabsManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/insights': typeof TabsInsightsRoute
  '/manage': typeof TabsManageRoute
}
export interface FileRoutesByTo {
  '/insights': typeof TabsInsightsRoute
  '/manage': typeof TabsManageRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/insights': typeof TabsInsightsRoute
  '/_tabs/manage': typeof TabsManageRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/insights' | '/manage'
  fileRoutesByTo: FileRoutesByTo
  to: '/insights' | '/manage' | '/'
  id: '__root__' | '/_tabs' | '/_tabs/insights' | '/_tabs/manage' | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/insights': {
      id: '/_tabs/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof TabsInsightsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/manage': {
      id: '/_tabs/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof TabsManageRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsInsightsRoute: typeof TabsInsightsRoute
  TabsManageRoute: typeof TabsManageRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsInsightsRoute: TabsInsightsRoute,
  TabsManageRoute: TabsManageRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
